name: ci

on:
  push:
    branches:
      - "main"
    tags: |
      # dynamically set the branch name and sha as a custom tag
      type=raw,value=${{ secrets.DOCKERHUB_USERNAME }}/{{branch}}/swarmtest:{{sha}}

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/swarmtest:${{ steps.meta.outputs.tags }}
      
      - 
        name: Deploy to Docker swarm
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: user@myswarm.com
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          deploy_path: ./
          stack_file_name: docker-compose.yaml
          keep_files: 5
          args: my_applicaion
